run:
  timeout: 5m
  tests: true
  build-tags: []
  skip-dirs: []
  skip-files: []

linters:
  enable:
    - errcheck
    - govet
    - revive
    - goimports
    - ineffassign
    - gosec
    - gocritic
    - misspell
    - stylecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment

  revive:
    severity: warning

  gosec:
    severity: medium

  gocritic:
    enabled-checks:
      - boolExprSimplify
      - commentedOutCode
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - nilValReturn
      - paramTypeCombine
      - sloppyReassign
      - stringsCompare
      - typeAssertChain
      - unnecessaryBlock
      - yodaStyleExpr

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - unparam
    - path: cmd/.*
      linters:
        - revive

  max-issues-per-linter: 0
  max-same-issues: 0
