version: '3'

vars:
  DATABASE_URL:
    sh: echo "${DATABASE_URL:-postgres://jobsity:jobsity123@localhost:5432/jobsity_chat?sslmode=disable}"
  DOCKER_COMPOSE_FILE: containers/docker-compose.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the applications
    cmds:
      - echo "Building chat-server..."
      - go build -o bin/chat-server ./cmd/chat-server
      - echo "Building stock-bot..."
      - go build -o bin/stock-bot ./cmd/stock-bot
      - echo "Build complete!"

  run:server:
    desc: Run the chat server
    cmds:
      - go run ./cmd/chat-server

  run:bot:
    desc: Run the stock bot
    cmds:
      - go run ./cmd/stock-bot

  tests:
    desc: Run all tests (unit + e2e)
    deps: [test:unit, test:e2e]

  test:unit:
    desc: Run unit tests with coverage
    cmds:
      - echo "ðŸ§ª Running unit tests..."
      - go test -v -race -short -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "âœ… Unit tests complete - coverage.html generated"

  test:e2e:
    desc: Run all E2E tests (requires Docker)
    cmds:
      - echo "ðŸ³ Running E2E tests..."
      - echo "âš ï¸  Ensure Docker daemon is running (docker info)"
      - echo "ðŸ“¦ First run will download PostgreSQL (~100MB) and RabbitMQ (~50MB)"
      - echo ""
      - go test -v -tags=e2e -timeout 10m ./tests/...
      - echo ""
      - echo "âœ… All E2E tests complete"

  coverage:
    desc: Show coverage report in terminal
    deps: [test:unit]
    cmds:
      - go tool cover -func=coverage.out

  lint:
    desc: Run linters
    cmds:
      - echo "Running golangci-lint..."
      - golangci-lint run
      - echo "Running go vet..."
      - go vet ./...
      - echo "Running go fmt..."
      - go fmt ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - gofmt -s -w .

  docker:build:
    desc: Build Docker images
    cmds:
      - echo "Building chat-server image..."
      - docker build -t jobsity-chat:latest -f containers/Dockerfile.chat-server .
      - echo "Building stock-bot image..."
      - docker build -t stock-bot:latest -f containers/Dockerfile.stock-bot .
      - echo "Docker images built successfully!"

  docker:run:
    desc: Run with Docker Compose
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} up -d
      - echo "Services started. Access chat at http://localhost:8080"
      - echo "RabbitMQ Management UI - http://localhost:15672 (guest/guest)"

  docker:stop:
    desc: Stop Docker Compose services
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} down

  docker:logs:
    desc: Show Docker Compose logs
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} logs -f

  docker:clean:
    desc: Stop and remove Docker volumes
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} down -v
      - echo "Docker containers and volumes removed"

  migrate:up:
    desc: Run database migrations up
    cmds:
      - echo "Running migrations..."
      - docker run --rm -v {{.PWD}}/migrations:/migrations --network host migrate/migrate:v4.17.0 -path=/migrations -database "{{.DATABASE_URL}}" up
      - echo "Migrations complete!"

  migrate:down:
    desc: Rollback last migration
    cmds:
      - echo "Rolling back migration..."
      - docker run --rm -v {{.PWD}}/migrations:/migrations --network host migrate/migrate:v4.17.0 -path=/migrations -database "{{.DATABASE_URL}}" down 1
      - echo "Rollback complete!"

  migrate:create:
    desc: Create new migration
    summary: |
      Create a new migration file
      Usage: task migrate-create NAME=create_users_table
    cmds:
      - echo "Creating migration - {{.NAME}}"
      - docker run --rm -v {{.PWD}}/migrations:/migrations migrate/migrate:v4.17.0 create -ext sql -dir /migrations -seq {{.NAME}}
      - echo "Migration files created in migrations/"

  migrate:force:
    desc: Force migration version
    summary: |
      Force the database to a specific migration version
      Usage: task migrate-force VERSION=1
    cmds:
      - echo "Forcing migration to version {{.VERSION}}..."
      - docker run --rm -v {{.PWD}}/migrations:/migrations --network host migrate/migrate:v4.17.0 -path=/migrations -database "{{.DATABASE_URL}}" force {{.VERSION}}
      - echo "Migration forced to version {{.VERSION}}!"

  migrate:status:
    desc: Check migration status
    cmds:
      - echo "Checking migration status..."
      - docker run --rm -v {{.PWD}}/migrations:/migrations --network host migrate/migrate:v4.17.0 -path=/migrations -database "{{.DATABASE_URL}}" version

  deps:
    desc: Download dependencies
    cmds:
      - echo "Downloading dependencies..."
      - go mod download
      - go mod tidy
      - echo "Dependencies updated!"

  tools:
    desc: Install development tools
    cmds:
      - echo "Installing tools..."
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - echo "Tools installed!"

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "Cleaning..."
      - rm -rf bin/
      - rm -f coverage.out coverage.html
      - echo "Clean complete!"

  dev:
    desc: Run development environment
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} up -d postgres rabbitmq
      - echo "Waiting for services to be ready..."
      - sleep 5
      - task migrate-up
      - echo "Starting chat server..."
      - task run-server

  init:
    desc: Initialize project
    summary: Install dependencies and development tools
    deps: [deps, install-tools]
    cmds:
      - echo "Project initialized!"

  # ============================================================================
  # Load Testing Commands (k6)
  # ============================================================================

  load:setup:
    desc: Setup load testing environment
    cmds:
      - echo "ðŸš€ Setting up load testing environment..."
      - echo "   Starting all services..."
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} up -d
      - echo "   Waiting for services to be ready..."
      - sleep 10
      - echo "âœ… Load testing environment ready!"
      - echo ""
      - echo "Available test scenarios:"
      - echo "  1. task load:run:connection     - Basic connection load (17 min)"
      - echo "  2. task load:run:chat           - Active chat load (13 min)"
      - echo "  3. task load:run:stock          - Stock bot stress (6.5 min)"
      - echo "  4. task load:run:spike          - Spike test (10 min)"
      - echo "  5. task load:run:soak           - Soak test (2+ hours)"
      - echo "  6. task load:run:multiroom      - Multi-room load (15 min)"
      - echo ""
      - echo "Quick test: task load:run:chat"

  load:run:connection:
    desc: Run Scenario 1 - Basic Connection Load
    summary: |
      Test maximum concurrent WebSocket connections
      Duration: 17 minutes (5m ramp + 10m hold + 2m down)
      Users: 0 â†’ 1000 â†’ 0
    cmds:
      - echo "ðŸ§ª Running Scenario 1: Basic Connection Load"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/01-connection-load.js

  load:run:chat:
    desc: Run Scenario 2 - Active Chat Load (Realistic)
    summary: |
      Simulate real users chatting
      Duration: 13 minutes
      Users: 500 across 10 chatrooms
    cmds:
      - echo "ðŸ’¬ Running Scenario 2: Active Chat Load"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/02-active-chat-load.js

  load:run:stock:
    desc: Run Scenario 3 - Stock Bot Stress Test
    summary: |
      Test stock command processing under load
      Duration: 6.5 minutes
      Users: 100 sending commands every 10 seconds
    cmds:
      - echo "ðŸ“ˆ Running Scenario 3: Stock Bot Stress"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/03-stock-bot-stress.js

  load:run:spike:
    desc: Run Scenario 4 - Spike Test (Resilience)
    summary: |
      Test sudden traffic surge and recovery
      Duration: 10 minutes
      Pattern: 100 â†’ 1000 â†’ 100 users
    cmds:
      - echo "âš¡ Running Scenario 4: Spike Test"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/04-spike-test.js

  load:run:soak:
    desc: Run Scenario 5 - Soak Test (Stability)
    summary: |
      Detect memory leaks and resource exhaustion
      Duration: 2+ hours (use SHORT_SOAK=true for 15 min test)
      Users: 300 continuous
    cmds:
      - echo "â° Running Scenario 5: Soak Test"
      - echo "âš ï¸  This will run for 2+ hours. Set SHORT_SOAK=true for 15-minute test."
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/05-soak-test.js

  load:run:soak-short:
    desc: Run Short Soak Test (15 minutes)
    cmds:
      - echo "â° Running Short Soak Test (15 minutes)"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm -e SHORT_SOAK=true k6 run --out experimental-prometheus-rw /scripts/scenarios/05-soak-test.js

  load:run:multiroom:
    desc: Run Scenario 6 - Multi-Room Load Distribution
    summary: |
      Test hub broadcast efficiency
      Duration: 15 minutes
      Users: 1000 across 50 chatrooms (Pareto distribution)
    cmds:
      - echo "ðŸ¢ Running Scenario 6: Multi-Room Load"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/06-multi-room-load.js

  load:run:all:
    desc: Run all load test scenarios sequentially
    summary: |
      Run all 6 scenarios one after another
      Total duration: ~1 hour (excluding soak test)
      Useful for comprehensive testing
    cmds:
      - echo "ðŸŽ¯ Running ALL load test scenarios"
      - echo "This will take approximately 1 hour"
      - echo ""
      - task load:run:connection
      - echo "âœ… Scenario 1 complete. Cooling down..."
      - sleep 30
      - task load:run:chat
      - echo "âœ… Scenario 2 complete. Cooling down..."
      - sleep 30
      - task load:run:stock
      - echo "âœ… Scenario 3 complete. Cooling down..."
      - sleep 30
      - task load:run:spike
      - echo "âœ… Scenario 4 complete. Cooling down..."
      - sleep 30
      - task load:run:multiroom
      - echo "âœ… Scenario 6 complete."
      - echo ""
      - echo "ðŸŽ‰ All load tests complete!"
      - echo "Check Grafana at http://localhost:3100 for results"

  load:results:
    desc: View load test results
    cmds:
      - echo "ðŸ“Š Load Test Results"
      - echo ""
      - echo "HTML Report: Open the generated HTML report"
      - docker run --rm -v containers_k6_results:/results alpine sh -c "ls -lh /results/"
      - echo ""
      - echo "Grafana Dashboard: http://localhost:3100"
      - echo "  - Import k6 dashboard (ID: 18595)"
      - echo "  - View your app metrics alongside k6 metrics"
      - echo ""
      - echo "Prometheus Queries:"
      - echo "  http://localhost:9090"

  load:clean:
    desc: Clean load test results
    cmds:
      - echo "ðŸ§¹ Cleaning load test results..."
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing down
      - docker volume rm containers_k6_results 2>/dev/null || true
      - echo "âœ… Cleaned!"
