version: '3'

vars:
  DATABASE_URL:
    sh: echo "${DATABASE_URL:-postgres://jobsity:jobsity123@localhost:5432/jobsity_chat?sslmode=disable}"
  DOCKER_COMPOSE_FILE: containers/docker-compose.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the applications
    cmds:
      - echo "Building chat-server..."
      - go build -o bin/chat-server ./cmd/chat-server
      - echo "Building stock-bot..."
      - go build -o bin/stock-bot ./cmd/stock-bot
      - echo "Build complete!"

  run:server:
    desc: Run the chat server
    cmds:
      - go run ./cmd/chat-server

  run:bot:
    desc: Run the stock bot
    cmds:
      - go run ./cmd/stock-bot

  tests:
    desc: Run all tests (unit + integration + e2e)
    deps: [test:unit, test:integration, test:e2e]

  test:unit:
    desc: Run unit tests with coverage
    vars:
      COVER_PKGS: >-
        jobsity-chat/internal/config,
        jobsity-chat/internal/domain,
        jobsity-chat/internal/handler,
        jobsity-chat/internal/messaging,
        jobsity-chat/internal/middleware,
        jobsity-chat/internal/observability,
        jobsity-chat/internal/repository/postgres,
        jobsity-chat/internal/service,
        jobsity-chat/internal/stock,
        jobsity-chat/internal/websocket
    cmds:
      - echo "ðŸ§ª Running unit tests..."
      - go test -race -coverprofile=coverage-unit.out -coverpkg={{.COVER_PKGS | replace "\n" "" | replace " " ""}} ./internal/...
      - go tool cover -html=coverage-unit.out -o coverage-unit.html
      - echo "âœ… Unit tests complete - coverage-unit.html generated"

  test:integration:
    desc: Run integration tests (requires Docker)
    cmds:
      - echo "ðŸ”Œ Running integration tests..."
      - echo "âš ï¸  Ensure Docker daemon is running (docker info)"
      - echo "ðŸ“¦ First run will download PostgreSQL (~100MB)"
      - echo ""
      - go test -race -tags=integration -coverprofile=coverage-integration.out -coverpkg=jobsity-chat/internal/repository/postgres -timeout 5m ./internal/repository/postgres/...
      - go tool cover -html=coverage-integration.out -o coverage-integration.html
      - echo "âœ… Integration tests complete - coverage-integration.html generated"

  test:e2e:
    desc: Run all E2E tests (requires Docker)
    vars:
      COVER_PKGS: >-
        jobsity-chat/internal/config,
        jobsity-chat/internal/domain,
        jobsity-chat/internal/handler,
        jobsity-chat/internal/messaging,
        jobsity-chat/internal/middleware,
        jobsity-chat/internal/observability,
        jobsity-chat/internal/repository/postgres,
        jobsity-chat/internal/service,
        jobsity-chat/internal/stock,
        jobsity-chat/internal/websocket
    cmds:
      - echo "ðŸ³ Running E2E tests..."
      - echo "âš ï¸  Ensure Docker daemon is running (docker info)"
      - echo "ðŸ“¦ First run will download PostgreSQL (~100MB) and RabbitMQ (~50MB)"
      - echo ""
      - go test -race -tags=e2e -coverprofile=coverage-e2e.out -coverpkg={{.COVER_PKGS | replace "\n" "" | replace " " ""}} -timeout 10m ./tests/e2e/...
      - go tool cover -html=coverage-e2e.out -o coverage-e2e.html
      - echo "âœ… E2E tests complete - coverage-e2e.html generated"

  test:all:
    desc: Run all tests and merge coverage
    cmds:
      - echo "ðŸ§ª Running all tests..."
      - task test:unit
      - task test:integration
      - task test:e2e
      - echo ""
      - echo "ðŸ“Š Merging coverage reports..."
      - |
        echo "mode: set" > coverage.out
        tail -n +2 coverage-unit.out >> coverage.out 2>/dev/null || true
        tail -n +2 coverage-integration.out >> coverage.out 2>/dev/null || true
        tail -n +2 coverage-e2e.out >> coverage.out 2>/dev/null || true
      - go tool cover -html=coverage.out -o coverage.html
      - echo "âœ… All tests complete - coverage.html generated"

  coverage:
    desc: Show coverage report in terminal
    deps: [test:unit]
    silent: true
    cmds:
      - go tool cover -func=coverage-unit.out

  coverage:all:
    desc: Show combined coverage report in terminal
    deps: [test:all]
    silent: true
    cmds:
      - go tool cover -func=coverage.out

  lint:
    desc: Run linters
    cmds:
      - echo "Running golangci-lint..."
      - golangci-lint run
      - echo "Running go vet..."
      - go vet ./...
      - echo "Running go fmt..."
      - go fmt ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - gofmt -s -w .

  docker:build:
    desc: Build Docker images
    cmds:
      - echo "Building chat-server image..."
      - docker build -t jobsity-chat:latest -f containers/Dockerfile.chat-server .
      - echo "Building stock-bot image..."
      - docker build -t stock-bot:latest -f containers/Dockerfile.stock-bot .
      - echo "Docker images built successfully!"

  docker:run:
    desc: Run with Docker Compose
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} up -d
      - echo "Services started. Access chat at http://localhost:8080"
      - echo "RabbitMQ Management UI - http://localhost:15672 (guest/guest)"

  docker:stop:
    desc: Stop Docker Compose services
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} down

  docker:logs:
    desc: Show Docker Compose logs
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} logs -f

  docker:clean:
    desc: Stop and remove Docker volumes
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} down -v
      - echo "Docker containers and volumes removed"

  migrate:up:
    desc: Run database migrations up
    cmds:
      - echo "Running migrations..."
      - docker run --rm -v {{.PWD}}/migrations:/migrations --network host migrate/migrate:v4.17.0 -path=/migrations -database "{{.DATABASE_URL}}" up
      - echo "Migrations complete!"

  migrate:down:
    desc: Rollback last migration
    cmds:
      - echo "Rolling back migration..."
      - docker run --rm -v {{.PWD}}/migrations:/migrations --network host migrate/migrate:v4.17.0 -path=/migrations -database "{{.DATABASE_URL}}" down 1
      - echo "Rollback complete!"

  migrate:create:
    desc: Create new migration
    summary: |
      Create a new migration file
      Usage: task migrate-create NAME=create_users_table
    cmds:
      - echo "Creating migration - {{.NAME}}"
      - docker run --rm -v {{.PWD}}/migrations:/migrations migrate/migrate:v4.17.0 create -ext sql -dir /migrations -seq {{.NAME}}
      - echo "Migration files created in migrations/"

  migrate:force:
    desc: Force migration version
    summary: |
      Force the database to a specific migration version
      Usage: task migrate-force VERSION=1
    cmds:
      - echo "Forcing migration to version {{.VERSION}}..."
      - docker run --rm -v {{.PWD}}/migrations:/migrations --network host migrate/migrate:v4.17.0 -path=/migrations -database "{{.DATABASE_URL}}" force {{.VERSION}}
      - echo "Migration forced to version {{.VERSION}}!"

  migrate:status:
    desc: Check migration status
    cmds:
      - echo "Checking migration status..."
      - docker run --rm -v {{.PWD}}/migrations:/migrations --network host migrate/migrate:v4.17.0 -path=/migrations -database "{{.DATABASE_URL}}" version

  deps:
    desc: Download dependencies
    cmds:
      - echo "Downloading dependencies..."
      - go mod download
      - go mod tidy
      - echo "Dependencies updated!"

  tools:
    desc: Install development tools
    cmds:
      - echo "Installing tools..."
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - echo "Tools installed!"

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "Cleaning..."
      - rm -rf bin/
      - rm -f coverage.out coverage.html
      - rm -f coverage-unit.out coverage-unit.html
      - rm -f coverage-integration.out coverage-integration.html
      - rm -f coverage-e2e.out coverage-e2e.html
      - echo "Clean complete!"

  dev:
    desc: Run development environment
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} up -d postgres rabbitmq
      - echo "Waiting for services to be ready..."
      - sleep 5
      - task migrate-up
      - echo "Starting chat server..."
      - task run-server

  init:
    desc: Initialize project
    summary: Install dependencies and development tools
    deps: [deps, install-tools]
    cmds:
      - echo "Project initialized!"

  # Load Testing Commands (k6)
  load:setup:
    desc: Setup load testing environment
    cmds:
      - echo "Setting up load testing environment..."
      - echo "Starting all services..."
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} up -d
      - echo "Waiting for services to be ready..."
      - sleep 10
      - echo "Load testing environment ready"

  load:run:chat:
    desc: Run Active Chat Load test
    cmds:
      - echo "Running Active Chat Load test"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/02-active-chat-load.js

  load:run:connection:
    desc: Run Connection Load test
    cmds:
      - echo "Running Connection Load test"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/01-connection-load.js

  load:run:stock:
    desc: Run Stock Bot Stress test
    cmds:
      - echo "Running Stock Bot Stress test"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/03-stock-bot-stress.js

  load:run:spike:
    desc: Run Spike Test
    cmds:
      - echo "Running Spike Test"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/04-spike-test.js

  load:run:soak:
    desc: Run Soak Test (2+ hours)
    cmds:
      - echo "Running Soak Test - This will take 2+ hours"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/05-soak-test.js

  load:run:soak-short:
    desc: Run Short Soak Test (15 minutes)
    cmds:
      - echo "Running Short Soak Test (15 minutes)"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm -e SHORT_SOAK=true k6 run --out experimental-prometheus-rw /scripts/scenarios/05-soak-test.js

  load:run:multiroom:
    desc: Run Multi-Room Load test
    cmds:
      - echo "Running Multi-Room Load test"
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing run --rm k6 run --out experimental-prometheus-rw /scripts/scenarios/06-multi-room-load.js

  load:run:all:
    desc: Run all load test scenarios
    silent: true
    cmds:
      - echo "Running all load test scenarios"
      - task load:run:connection
      - sleep 30
      - task load:run:chat
      - sleep 30
      - task load:run:stock
      - sleep 30
      - task load:run:spike
      - sleep 30
      - task load:run:multiroom
      - echo "All load tests complete"

  load:clean:
    desc: Clean load test results
    cmds:
      - echo "Cleaning load test results..."
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} --profile load-testing down
      - docker volume rm containers_k6_results 2>/dev/null || true
      - echo "Cleaned"
